#!/usr/bin/python

import argparse
import csv
import pandas

__author__ = 'dlb'
 
parser = argparse.ArgumentParser(description='Csv to Dxf Conversion, 1.0')
parser.add_argument('-i','--input', help='infile',required=True)
parser.add_argument('-o','--output',help='outfile', required=True)
args = parser.parse_args()
 
## show values ##
print ("Input file: %s" % args.input )
print ("Output file: %s" % args.output )

## process files ##

# create/overwrite output file
outfile = open(args.output, "w");
outfile.write('  0\n')
outfile.write('SECTION\n')
outfile.write('  2\n')
outfile.write('ENTITIES\n')
outfile.close()

# open csv file and process contents
reader = csv.reader(open(args.input))
for pnum, northing, easting, elevation, desc in reader:
	outfile = open(args.output, "a");
	outfile.write('  0\n')
	outfile.write('POINT\n')
	outfile.write('  8\n')
	outfile.write('PT\n')
	outfile.write(' 62\n')
	outfile.write('     7\n')
	outfile.write(' 10\n')
	outfile.write(str(easting) + '\n')
	outfile.write(' 20\n')
	outfile.write(str(northing) + '\n')
	outfile.write(' 30\n')
	outfile.write(str(elevation) + '\n')
	outfile.write('  0\n')
	outfile.write('TEXT\n')
	outfile.write('  8\n')
	outfile.write('PN\n')
	outfile.write(' 62\n')
	outfile.write('     2\n')
	outfile.write(' 10\n')
	outfile.write(str(easting) + '\n')
	outfile.write(' 20\n')
	outfile.write(str(northing) + '\n')
	outfile.write(' 30\n')
	outfile.write('0\n')
	outfile.write(' 40\n')
	outfile.write('0.1\n')
	outfile.write('  1\n')
	outfile.write(str(pnum) + '\n')
	outfile.write(' 72\n')
	outfile.write('     0\n')
	outfile.write(' 11\n')
	outfile.write(str(easting) + '\n')
	outfile.write(' 21\n')
	outfile.write(str(northing) + '\n')
	outfile.write(' 31\n')
	outfile.write('0\n')
	outfile.write(' 73\n')
	outfile.write('     1\n')
	outfile.write('  0\n')
	outfile.write('TEXT\n')
	outfile.write('  8\n')
	outfile.write('EL\n')
	outfile.write(' 62\n')
	outfile.write('     4\n')
	outfile.write(' 10\n')
	outfile.write(str(easting) + '\n')
	outfile.write(' 20\n')
	outfile.write(str(northing) + '\n')
	outfile.write(' 30\n')
	outfile.write('0\n')
	outfile.write(' 40\n')
	outfile.write('0.1\n')
	outfile.write('  1\n')
	outfile.write(str(elevation) + '\n')
	outfile.write('72\n')
	outfile.write('  2\n')
	outfile.write(' 11\n')
	outfile.write(str(easting) + '\n')
	outfile.write(' 21\n')
	outfile.write(str(northing) + '\n')
	outfile.write(' 31\n')
	outfile.write('0\n')
	outfile.write(' 73\n')
	outfile.write('     3\n')
	outfile.write('  0\n')
	outfile.write('TEXT\n')
	outfile.write('  8\n')
	outfile.write('DE\n')
	outfile.write(' 62\n')
	outfile.write('     3\n')
	outfile.write(' 10\n')
	outfile.write(str(easting) + '\n')
	outfile.write(' 20\n')
	outfile.write(str(northing) + '\n')
	outfile.write(' 30\n')
	outfile.write('0\n')
	outfile.write(' 40\n')
	outfile.write('0.1\n')
	outfile.write('  1\n')
	outfile.write(str(desc) + '\n')
	outfile.write('72\n')
	outfile.write('  0\n')
	outfile.write(' 11\n')
	outfile.write(str(easting) + '\n')
	outfile.write(' 21\n')
	outfile.write(str(northing) + '\n')
	outfile.write(' 31\n')
	outfile.write('0\n')
	outfile.write(' 73\n')
	outfile.write('     3\n')

outfile.write('  0\n')
outfile.write('ENDSEC\n')
outfile.write('  0\n')
outfile.write('EOF\n')
outfile.close()
print ("Done\n")
